### ISSUE TITLE
CFs do not seem sufficiently lazy

### ISSUE THREAD

**Issue by tebello-thejane** [mvr/cf#3]
The following example in GHCi seems to hang and run at maximum CPU:

```
(sqrt 2 :: CF) * (sqrt 2 :: CF)
```

Simply showing `sqrt 2` produces the right answer, although it is awfully slow (I will have to verify if this is due to Gosper's algorithm or a bug in this package).

**Comment by mvr** [comment]
Here we are running into one of the inherent problems with this representation of the reals. If you try `let (CF terms) = (sqrt 2 :: CF) * (sqrt 2 :: CF)`, you will see that it is actually computing terms of a continued fraction expansion for 2! The problem here comes when it tries to print out a decimal result, it gets stuck on the first digit. Each additional term gets us a better interval where the result can lie, but this interval always straddles `2`, so we can never tell whether to output a `1` or a `2` for the first digit. If you instead try `(sqrt 2 :: CF) * (sqrt 2 :: CF) * (sqrt 2 :: CF)`, we do get a result.

Computing `sqrt 2` is slow because it is actually doing `exp (log 2 * 0.5)`. If we could detect that the argument is a rational number, we could find the `sqrt` very quickly using something like https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Continued_fraction_expansion
